### ISSUE TITLE
commit message, Textile parsing

### ISSUE THREAD

**Issue by roykolak** [roykolak/dashy#17]
Just thought of a nice addition to Dashy. Since we (or at least I) tend to use Textile markup in our commit messages to have them show up all pretty in Chili it might also be cool if Dashy supported some (small set like bold face, italic, item lists, pre tags) when displaying commit messages during build time.

-- Joris Kraak

**Comment by bauglir** [comment]
I am torn a bit on whether it would actually have to be Textile or Markdown or something similar, since I guess the syntax you'd want to support is common to more languages than just the ones listed.

**Comment by roykolak** [comment]
Decided to use Textile based on the fact that Redmine uses it.@tomkersten brought up a good point that it isn't really a big deal because bulleted lists are formatted the same way in Textile and Markdown and bullets would be the main reason to parse commit messages.
