### ISSUE TITLE
Try to load a refresh.txt

### ISSUE THREAD

**Issue by Weltraumschaf** [roykolak/dashy#19]
Nice tool! After setup it looks like it works correct, but in Firebug I saw that it tries to load a refresh.txt. For what is this file good?

**Comment by roykolak** [comment]
Hey there Weltraumschaf, refresh.txt is related to deploying new versions of Dashy. The idea is that if Dashy is able to load refresh.txt, then it should trigger a refresh. 

The deployment script creates refresh.txt in Dashy's root, then waits about 7 seconds, then deletes it. The 7 second wait period is to be absolutely sure that Dashy has refreshed at least one.

**Comment by Weltraumschaf** [comment]
Ok. A backdraw is that the sysadmins will complain about that spam in the webservers log. Maybe you can check a versions file where you put in a version number and decide on that to reload?

**Comment by Weltraumschaf** [comment]
Project seams dead :/
